version: '3'
services:
  web:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .

    # Mapping of container port to host

    ports:
      - "8910:8910"
    # Mount volume
    volumes:
      - "/go-emp/:/go-employee"

    # Link database container to app container
    # for reachability.
    links:
      - "database:goblog"

  database:

    # image to fetch from docker hub
    image:mysql-goblog

    # Environment variables for startup script
    # container will use these variables
    # to start the container with these define variables.
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=Mysqlroot123"
      - "MYSQL_DATABASE=goblog"
    # Mount init.sql file to automatically run
    # and create tables for us.
    # everything in docker-entrypoint-initdb.d folder
    # is executed as soon as container is up nd running.
    volumes:
      - "/go-emp/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
